### ISSUE TITLE
Code organization improvements

### ISSUE THREAD

**Issue by olivierobert** [lacuong2009/Nimble#5]
There are lots of boilerplate files which should be removed as these are not relevant to the application:

![Screen Shot 2564-06-10 at 16 58 33](https://user-images.githubusercontent.com/696529/121505712-42db8380-ca0d-11eb-98a1-022b15568ada.png)

On the frontend side of things, the assets folder can be cleaned up:

![image](https://user-images.githubusercontent.com/696529/121509387-c9459480-ca10-11eb-8c15-218f3a7b473a.png)

- Removing `.gitkeep`
- Rename images based on their use case e.g. `man.png` -> `user_avatar.png`, `img_avatar2.png` -> `login_avatar.png`.

**Comment by lacuong2009** [comment]
I will do that, Thanks for feeback

**Comment by lacuong2009** [comment]
Hi @olivierobert,

I have removed boilerplate files. Please review it. 
Also, I close this ticket.
