### ISSUE TITLE
Keywords listing is not scoped to the current user

### ISSUE THREAD

**Issue by olivierobert** [lacuong2009/Nimble#6]
When accessing the list of keyword, a user can see all keywords uploaded by all users 😨 

![image](https://user-images.githubusercontent.com/696529/121506387-d90fa980-ca0d-11eb-95fe-2e26d5dbe96b.png)

The following controller method returns all records without user scoping:

https://github.com/lacuong2009/Nimble/blob/e45bed30a88610db2aea3a945b346fb3049f11b2/back-end/app/Http/Controllers/KeywordController.php#L148-L155

**Comment by lacuong2009** [comment]
Hi, @olivierobert.

I have fixed it. Please review it.  Thanks you

**Comment by olivierobert** [comment]
Making a fix in a PR would have been better. In terms of functionality, the changes cover the requirements.
