### ISSUE TITLE
Two instances of GoogleSearchClient created in CrawlerJob

### ISSUE THREAD

**Issue by olivierobert** [lacuong2009/Nimble#8]
In the class `CrawlerJob`, the method `editKeyword` actually relies on two instances of `GoogleSearchClient`:

`$res = (new GoogleSearchClient())->get($google);` is used to store the HTML content

https://github.com/lacuong2009/Nimble/blob/e45bed30a88610db2aea3a945b346fb3049f11b2/back-end/app/Jobs/CrawlerJob.php#L59-L72

`getResults` also create a new GoogleSearchClient instance:

https://github.com/lacuong2009/Nimble/blob/e45bed30a88610db2aea3a945b346fb3049f11b2/back-end/app/Jobs/CrawlerJob.php#L123-L129

First, this is incorrect as the HTML stored can be different from the parsed HTML used to count the links. This is a limitation on using the Search API. An actual crawler/scraper would only need one HTML source. 

Second, reusing `GoogleSearchClient` twice is confusing. The second `GoogleSearchClient` instance only uses to make a GET request via `GuzzleHttp\Client`. It does not use `private $url = 'https://www.googleapis.com/customsearch/v1';` define in the class. That's why it needs to provide its own URL.

**Comment by lacuong2009** [comment]
Hi @olivierobert,
I have updated the store only HTML structure.
Also, I have to update the instance HTTP client for requests search results and get HTML to the google results page.

Please review and give me your feedback.

**Comment by olivierobert** [comment]
Extracting to a separate method with its own instance client (and not `GoogleSearchClient`) is better indeed :-)
